# Generated by Django 5.2.6 on 2026-08-12 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0001_initial'),
        ('employee', '0002_alter_employee_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='employee_code',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterUniqueTogether(
            name='employee',
            unique_together={('company', 'employee_code')},
        ),
    ]
