# Generated by Django 6.1 on 2026-08-13 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('role', '0003_rolepermission'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='is_system_role',
            field=models.BooleanField(default=True),
        ),
    ]
