# Generated by Django 6.1 on 2026-08-13 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('role', '0004_alter_role_is_system_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='role',
            name='code',
        ),
        migrations.RemoveField(
            model_name='role',
            name='company',
        ),
        migrations.RemoveField(
            model_name='role',
            name='description',
        ),
        migrations.RemoveField(
            model_name='role',
            name='is_system_role',
        ),
        migrations.AddField(
            model_name='role',
            name='display_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='role',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
