# Generated by Django 5.2.6 on 2026-08-15 09:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('permission_set', '0002_permissionsetpermission'),
        ('role', '0005_remove_role_code_remove_role_company_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RolePermissionSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('permission_set', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='role_permission_sets', to='permission_set.permissionset')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='role_permission_sets', to='role.role')),
            ],
            options={
                'verbose_name_plural': 'Role Permission Sets',
                'ordering': ['-created_at'],
                'unique_together': {('role', 'permission_set')},
            },
        ),
    ]
