# Generated by Django 5.2.6 on 2026-08-15 09:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('role', '0006_rolepermissionset'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RolePermission',
        ),
    ]
