# Generated by Django 6.1 on 2026-08-15 06:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('department', '0003_department_code_alter_department_unique_together'),
        ('designation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='designation',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='designations', to='department.department'),
        ),
    ]
