# Generated by Django 5.2.6 on 2026-08-15 09:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('designation', '0002_designation_department'),
        ('permission_set', '0002_permissionsetpermission'),
    ]

    operations = [
        migrations.CreateModel(
            name='DesignationPermissionSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('designation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='designation_permission_sets', to='designation.designation')),
                ('permission_set', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='designation_permission_sets', to='permission_set.permissionset')),
            ],
            options={
                'verbose_name_plural': 'Designation Permission Sets',
                'ordering': ['-created_at'],
                'unique_together': {('designation', 'permission_set')},
            },
        ),
    ]
