# Generated by Django 5.2.6 on 2026-08-15 09:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='department',
        ),
    ]
