# Generated by Django 6.1 on 2026-08-18 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approve', 'Approve'), ('rejected', 'Rejected')], default='approve', max_length=20),
        ),
    ]
