# Generated by Django 6.1 on 2026-08-11 05:19

import django.db.models.deletion
from django.db import migrations, models


def set_default_role_or_clean(apps, schema_editor):
    User = apps.get_model('user', 'User')
    Role = apps.get_model('role', 'Role')
    Company = apps.get_model('company', 'Company')
    
    users_without_role = User.objects.filter(role__isnull=True)
    if users_without_role.exists():
        company, _ = Company.objects.get_or_create(
            name="Default Company",
            defaults={"email": "default@company.com"}
        )
        role, _ = Role.objects.get_or_create(
            company=company,
            name="Default Role",
            defaults={"description": "Default role for existing users"}
        )
        users_without_role.update(role=role)


class Migration(migrations.Migration):

    dependencies = [
        ('role', '0001_initial'),
        ('user', '0002_user_role'),
    ]

    operations = [
        migrations.RunPython(set_default_role_or_clean, reverse_code=migrations.RunPython.noop),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='users', to='role.role'),
        ),
    ]
