# Generated by Django 5.2.6 on 2026-08-12 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0001_initial'),
        ('department', '0002_remove_department_manager'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='code',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterUniqueTogether(
            name='department',
            unique_together={('company', 'code')},
        ),
    ]
