# Generated by Django 5.2.6 on 2026-08-15 09:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('department', '0003_department_code_alter_department_unique_together'),
        ('permission_set', '0002_permissionsetpermission'),
    ]

    operations = [
        migrations.CreateModel(
            name='DepartmentPermissionSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='department_permission_sets', to='department.department')),
                ('permission_set', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='department_permission_sets', to='permission_set.permissionset')),
            ],
            options={
                'verbose_name_plural': 'Department Permission Sets',
                'ordering': ['-created_at'],
                'unique_together': {('department', 'permission_set')},
            },
        ),
    ]
