# Generated by Django 5.2.6 on 2026-08-15 08:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('permission', '0002_update_permission_schema'),
        ('permission_set', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PermissionSetPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('permission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permission_set_permissions', to='permission.permission')),
                ('permission_set', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permission_set_permissions', to='permission_set.permissionset')),
            ],
            options={
                'verbose_name_plural': 'Permission Set Permissions',
                'ordering': ['-created_at'],
                'unique_together': {('permission_set', 'permission')},
            },
        ),
    ]
